### ISSUE TITLE
Cannot pan scene with Alt + right drag in Win10

### ISSUE THREAD

**Issue by samueldy** [iRASPA/iRASPA-QT#1]
Thanks so much for the wonderful product! I can't wait to use this for my research.

I'm running iRASPA 1.1.15 (build 20, from the Windows Store) on Windows 1809. I can rotate the scene, but cannot pan using Alt + right mouse drag as described in the help. When I try, it simply opens the context menu. Is there another way to pan?

Thanks,
-- Sam

![iraspa-qt-win10-no_pan](https://user-images.githubusercontent.com/43612797/70732560-a8df3180-1cd6-11ea-8fc4-6bb1c7ce1399.gif)

**Comment by dubbelda** [comment]
This is finally implemented (1.1.22 )and should work:
Alt + right-drag: pan/tilt
Ctrl + right-drag: truck/pedestal
