### ISSUE TITLE
[feature request] more control over unit cell box upon replication

### ISSUE THREAD

**Issue by SimonEnsemble** [iRASPA/iRASPA-QT#2]
iRASPA is awesome, thank you for making it open source!

![image](https://user-images.githubusercontent.com/30643894/105428883-347aff80-5c05-11eb-91f1-2d35a656b0ba.png)

as a feature request, would be cool if we had more control over the unit cell box upon replicating the crystal:
(i) [current behavior] replicate box with the atoms
(ii) keep only original "home" unit cell in the corner
(iii) make new unit cell box around the whole thing (just one parallelogram)

is it ok with you if I post feature requests like this?

**Comment by dubbelda** [comment]
Sure, you can post feature requests. For this one, the alternative way of doing this, is to use multiple structure. This gives great flexibility. However, there is a bug where copy/paste of the structure does not work. I will fix that.
The alternative way, is to go to the atoms-tab, selecting no atoms, and click "Selection" -> "CopyToNewMovie".

<img width="1222" alt="NewMovie" src="https://user-images.githubusercontent.com/5294576/105705180-203e4780-5f10-11eb-862f-9173160ac9db.png">


Now you have a second structure with just the same cell. So you set the cell options for that

<img width="1338" alt="SetCellOptions" src="https://user-images.githubusercontent.com/5294576/105705195-29c7af80-5f10-11eb-8f50-9151e0c6a6f8.png">

**Comment by dubbelda** [comment]
iRASPA 2.0.2 is available in the windows store as an update. The general approach outlined above works again (bug is fixed).

**Comment by SimonEnsemble** [comment]
thanks!
I am on Linux, so I will have to wait for the `snap` update, I suppose.
the trick above did not work on my Linux machine.

for now, I can replicate in other software and reload the replicated `.cif`.

also, we are citing your paper for a surface area calculation
>  gravimetric surface area (defined by a potential energy contour of a xenon probe adsorbate in the pores, computed in iRASPA \cite{Dubbeldam2015})

but couldn't find documentation on which potential energy contour iRASPA uses. just a suggestion to add this to the docs. I assume energy = 0?
thanks!

**Comment by dubbelda** [comment]
The linux snap is also available and the rpm/deb package in the release page are also updated to 2.0.2.

The surface area is not the usual geometric surface area, but rather the area of the PES at energy=0 for a very simplistic force field (DREIDING/UFF like).
