### ISSUE TITLE
[feature request] custom bond and atom info

### ISSUE THREAD

**Issue by aliraza-ece** [iRASPA/iRASPA-QT#3]
Thank you for this wonderful project. This is really helpful for visualization.  I am importing the `.cif` file of a MOF that contains charges but the software is not importing those charges and setting q to zero.  I also exported a MOF from included public database CoRE MOF v1.0 DDEC to a `.cif `file (`right_click `and `export to CIF`on `Atoms` tab and then imported that file. Again the `.cif` file contained charges but the software did not load them. I am using version 2.0.1 (build 97) on Windows 10.  I've attached the `.cif` file (converted it to .txt for upload). 

I also think it would be awesome if we could load custom bond and atom information and use them for annotation. 

[ABAVIJ_clean.cif.txt](https://github.com/iRASPA/iRASPA-QT/files/5854811/ABAVIJ_clean.cif.txt)

**Comment by dubbelda** [comment]
The charge-reading is added, and will be available in the next release (in a couple of days).

Bond-annotation would be nice, but we lack the time to add that in the immediate future.

**Comment by dubbelda** [comment]
iRASPA 2.0.2 is available in the windows store as an update.
