### ISSUE TITLE
XYZ file import and export

### ISSUE THREAD

**Issue by ngantzler** [iRASPA/iRASPA-QT#4]
I am running iRASPA v2.0.2 on Linux, and I am having trouble with the features related to `XYZ` file formats.
1. I see the option to export as `XYZ` file format from the right-click drop down menu, but I am unable to find the output file location. 
2. I am also unable to import structures with `.xyz` file extensions.

**Comment by dubbelda** [comment]
In v2.0.3 (snap linux) you should be able to read xyz-files. In the atomView-pane you could also be able to export to xyz-format.

**Comment by ngantzler** [comment]
I just tried it out, and both functions are working for me. Thank you!
