### ISSUE TITLE
collage of structures

### ISSUE THREAD

**Issue by SimonEnsemble** [iRASPA/iRASPA-QT#5]
love this collage of structures!
![image](https://user-images.githubusercontent.com/30643894/119074716-5bbfbe80-b9a4-11eb-83f9-7996fb7cb4d0.png)

good for science too, since this makes sure the pore sizes are directly comparable if comparing multiple MOFs, as opposed to making separate visualizations of each structure, without control over the length-scale of the camera.

is there documentation for how to do this?

when I select two crystal structures for importing, they show up together but they are on top of each other and overlapping. is there a way to provide the origin of the unit cell in the `.cif` file or?
appreciate any help. iRASPA rocks! :rocket: 

PS was thinking adding scale bars for e.g. 1 nm would be informative too for publications.

**Comment by dubbelda** [comment]
After importing the three structures, go on the top-left to the second of the three tabs. Here you can set properties per framework. Then, for each structure, set the origin (on the right, cell-tab, Cell/Bounding-Box properties). You can also set the orientation of each framework with respect to the others.

**Comment by SimonEnsemble** [comment]
thank you, it works!
